wireguard: Fix totalram_pages usage
../net/wireguard/src/ratelimiter.c:187:22: error: invalid operands to binary expression ('unsigned long (void)' and 'int')
                        (totalram_pages() << PAGE_SHIFT) /
                         ~~~~~~~~~~~~~~~~ ^  ~~~~~~~~~~
../include/linux/log2.h:163:19: note: expanded from macro 'roundup_pow_of_two'
                (1UL << (ilog2((n) - 1) + 1))   \
                                ^
../include/linux/log2.h:85:4: note: expanded from macro 'ilog2'
                (n) & (1ULL << 61) ? 61 :       \
                 ^
../include/linux/kernel.h:788:17: note: expanded from macro 'max_t'
        type __max2 = (y);                      \
                       ^

Change-Id: I9b1f0a254078aaf5a043b89cfed6c9a865f37733
Signed-off-by: Reinazhard <muh.alfarozy@gmail.com>
(cherry picked from commit 7d6a241d7a73b5aa729d4d21887941139ee0cb61)